import React, { createContext, useContext, useState, useEffect } from 'react';

export const translations = {
  uz: {
    // Role screen
    welcome: "Xush kelibsiz!",
    selectRole: "Rolingizni tanlang",
    roleCaller: "Foydalanuvchi",
    roleCallerDesc: "Yordam so'rash",
    roleDriver: "Haydovchi",
    roleDriverDesc: "Xizmat ko'rsatish",
    roleNote: "Haydovchilar faqat admin tomonidan qo'shiladi",
    // Login
    phoneTab: "Telefon",
    emailTab: "Email",
    enterPhone: "Telefon raqamingizni kiriting",
    enterCode: "SMS kodni kiriting",
    sendCode: "Kod yuborish",
    verify: "Tasdiqlash",
    resendIn: "Qayta yuborish",
    sec: "s",
    resend: "Qayta yuborish",
    firstName: "Ism",
    lastName: "Familiya",
    continue: "Davom etish",
    back: "← Orqaga",
    driverPhone: "Haydovchi telefon raqami",
    driverCode: "Login kod (8 ta belgi)",
    signIn: "Kirish",
    enterEmail: "Email kiriting",
    enterPassword: "Parol kiriting",
    confirmPassword: "Parolni tasdiqlang",
    register: "Ro'yxatdan o'tish",
    login: "Kirish",
    // Home
    hello: "Salom",
    location: "Joylashuv aniqlanmoqda...",
    searchServices: "Xizmatlarni qidiring...",
    services: "Xizmatlar",
    all: "Barchasi",
    ambulance: "Tez Yordam",
    pharmacy: "Dorixona",
    police: "Politsiya",
    fire: "Yong'in",
    activeEmergency: "Faol so'rov",
    activeEmergencySub: "Holatni ko'rish uchun bosing",
    lastCall: "Oxirgi so'rov",
    comingSoon: "Tez kunda",
    comingSoonMsg: "Bu xizmat tez kunda ishga tushadi!",
    locationPickerTitle: "Joylashuvni tanlang",
    locationPickerSub: "Xaritada o'z joyingizni belgilang",
    saveLocation: "Shu joyni saqlash",
    call: "Qo'ng'iroq",
    // Emergency
    waitingGps: "📍 Joylashuv aniqlanmoqda...",
    sendEmergency: "TEZ YORDAM CHAQIRISH",
    sendPolice: "POLITSIYA CHAQIRISH",
    sendFire: "YONG'IN CHAQIRISH",
    sending: "Yuborilmoqda...",
    waitingLocation: "📍 Joylashuv kutilmoqda...",
    additionalInfo: "Qo'shimcha ma'lumot (ixtiyoriy)...",
    // Status labels
    statusNew: "Yangi",
    statusConfirmed: "Tasdiqlandi",
    statusAssigned: "Haydovchi tayinlandi",
    statusOnWay: "Yo'lda",
    statusArrived: "Keldi",
    statusCompleted: "Tugatildi",
    statusCancelled: "Bekor qilindi",
    // Notifications
    notifications: "Bildirishnomalar",
    latestNews: "Oxirgi yangiliklar",
    noNotifications: "Hozircha bildirishnomalar yo'q",
    minsAgo: "daqiqa oldin",
    hoursAgo: "soat oldin",
    daysAgo: "kun oldin",
    // Profile
    account: "Hisob",
    fullName: "To'liq ism",
    edit: "Tahrirlash",
    phone: "Telefon",
    email: "Email",
    callHistory: "Chaqiruvlar tarixi",
    viewAllCalls: "Barcha chaqiruvlarni ko'rish",
    feedback: "Fikr va takliflar",
    feedbackSub: "Ilovani yaxshilashga yordam bering",
    settings: "Sozlamalar",
    settingsSub: "Ilova sozlamalari",
    version: "Versiya",
    logout: "Chiqish",
    editName: "Ismni tahrirlash",
    save: "Saqlash",
    cancel: "Bekor qilish",
    settingsTitle: "Sozlamalar",
    darkMode: "Tungi rejim",
    soundNotif: "Ovozli bildirishnoma",
    language: "Til",
    nameSaved: "Ism saqlandi",
    // Confirmation
    driverOnWay: "Haydovchi yo'lda",
    waitingDriver: "Haydovchi kutilmoqda...",
    cancelEmergency: "Bekor qilish",
    cancelConfirm: "So'rovni bekor qilmoqchimisiz?",
    yes: "Ha",
    no: "Yo'q",
    // Feedback
    feedbackTitle: "Fikr bildiring",
    feedbackPlaceholder: "Izohingizni yozing...",
    sendFeedback: "Yuborish",
  },
  ru: {
    welcome: "Добро пожаловать!",
    selectRole: "Выберите вашу роль",
    roleCaller: "Пользователь",
    roleCallerDesc: "Вызвать помощь",
    roleDriver: "Водитель",
    roleDriverDesc: "Оказание услуг",
    roleNote: "Водители добавляются только администратором",
    phoneTab: "Телефон",
    emailTab: "Email",
    enterPhone: "Введите номер телефона",
    enterCode: "Введите SMS код",
    sendCode: "Отправить код",
    verify: "Подтвердить",
    resendIn: "Отправить снова через",
    sec: "с",
    resend: "Отправить снова",
    firstName: "Имя",
    lastName: "Фамилия",
    continue: "Продолжить",
    back: "← Назад",
    driverPhone: "Телефон водителя",
    driverCode: "Код входа (8 символов)",
    signIn: "Войти",
    enterEmail: "Введите email",
    enterPassword: "Введите пароль",
    confirmPassword: "Подтвердите пароль",
    register: "Регистрация",
    login: "Войти",
    hello: "Привет",
    location: "Определение местоположения...",
    searchServices: "Поиск услуг...",
    services: "Услуги",
    all: "Все",
    ambulance: "Скорая помощь",
    pharmacy: "Аптека",
    police: "Полиция",
    fire: "Пожарная",
    activeEmergency: "Активный вызов",
    activeEmergencySub: "Нажмите, чтобы просмотреть статус",
    lastCall: "Последний вызов",
    comingSoon: "Скоро",
    comingSoonMsg: "Эта услуга скоро будет доступна!",
    locationPickerTitle: "Выберите местоположение",
    locationPickerSub: "Отметьте своё место на карте",
    saveLocation: "Сохранить это место",
    call: "Звонок",
    waitingGps: "📍 Определение местоположения...",
    sendEmergency: "ВЫЗВАТЬ СКОРУЮ",
    sendPolice: "ВЫЗВАТЬ ПОЛИЦИЮ",
    sendFire: "ВЫЗВАТЬ ПОЖАРНЫХ",
    sending: "Отправка...",
    waitingLocation: "📍 Ожидание местоположения...",
    additionalInfo: "Дополнительная информация (необязательно)...",
    statusNew: "Новый",
    statusConfirmed: "Подтверждено",
    statusAssigned: "Водитель назначен",
    statusOnWay: "В пути",
    statusArrived: "Прибыл",
    statusCompleted: "Завершено",
    statusCancelled: "Отменено",
    notifications: "Уведомления",
    latestNews: "Последние обновления",
    noNotifications: "Пока нет уведомлений",
    minsAgo: "мин. назад",
    hoursAgo: "ч. назад",
    daysAgo: "д. назад",
    account: "Аккаунт",
    fullName: "Полное имя",
    edit: "Изменить",
    phone: "Телефон",
    email: "Email",
    callHistory: "История вызовов",
    viewAllCalls: "Просмотреть все вызовы",
    feedback: "Отзывы и предложения",
    feedbackSub: "Помогите улучшить приложение",
    settings: "Настройки",
    settingsSub: "Настройки приложения",
    version: "Версия",
    logout: "Выйти",
    editName: "Изменить имя",
    save: "Сохранить",
    cancel: "Отмена",
    settingsTitle: "Настройки",
    darkMode: "Тёмный режим",
    soundNotif: "Звуковые уведомления",
    language: "Язык",
    nameSaved: "Имя сохранено",
    driverOnWay: "Водитель в пути",
    waitingDriver: "Ожидание водителя...",
    cancelEmergency: "Отменить",
    cancelConfirm: "Вы хотите отменить вызов?",
    yes: "Да",
    no: "Нет",
    feedbackTitle: "Оставить отзыв",
    feedbackPlaceholder: "Напишите ваш комментарий...",
    sendFeedback: "Отправить",
  },
  en: {
    welcome: "Welcome!",
    selectRole: "Select your role",
    roleCaller: "User",
    roleCallerDesc: "Request help",
    roleDriver: "Driver",
    roleDriverDesc: "Provide service",
    roleNote: "Drivers are added by admin only",
    phoneTab: "Phone",
    emailTab: "Email",
    enterPhone: "Enter your phone number",
    enterCode: "Enter SMS code",
    sendCode: "Send Code",
    verify: "Verify",
    resendIn: "Resend in",
    sec: "s",
    resend: "Resend",
    firstName: "First Name",
    lastName: "Last Name",
    continue: "Continue",
    back: "← Back",
    driverPhone: "Driver phone number",
    driverCode: "Login code (8 characters)",
    signIn: "Sign In",
    enterEmail: "Enter email",
    enterPassword: "Enter password",
    confirmPassword: "Confirm password",
    register: "Register",
    login: "Login",
    hello: "Hello",
    location: "Detecting location...",
    searchServices: "Search services...",
    services: "Services",
    all: "All",
    ambulance: "Ambulance",
    pharmacy: "Pharmacy",
    police: "Police",
    fire: "Fire",
    activeEmergency: "Active Request",
    activeEmergencySub: "Tap to view status",
    lastCall: "Last Call",
    comingSoon: "Coming Soon",
    comingSoonMsg: "This service will be available soon!",
    locationPickerTitle: "Select Location",
    locationPickerSub: "Mark your location on the map",
    saveLocation: "Save this location",
    call: "Call",
    waitingGps: "📍 Detecting location...",
    sendEmergency: "CALL AMBULANCE",
    sendPolice: "CALL POLICE",
    sendFire: "CALL FIRE DEPT",
    sending: "Sending...",
    waitingLocation: "📍 Waiting for location...",
    additionalInfo: "Additional info (optional)...",
    statusNew: "New",
    statusConfirmed: "Confirmed",
    statusAssigned: "Driver assigned",
    statusOnWay: "On the way",
    statusArrived: "Arrived",
    statusCompleted: "Completed",
    statusCancelled: "Cancelled",
    notifications: "Notifications",
    latestNews: "Latest updates",
    noNotifications: "No notifications yet",
    minsAgo: "mins ago",
    hoursAgo: "hrs ago",
    daysAgo: "days ago",
    account: "Account",
    fullName: "Full Name",
    edit: "Edit",
    phone: "Phone",
    email: "Email",
    callHistory: "Call History",
    viewAllCalls: "View all calls",
    feedback: "Feedback",
    feedbackSub: "Help us improve the app",
    settings: "Settings",
    settingsSub: "App settings",
    version: "Version",
    logout: "Logout",
    editName: "Edit Name",
    save: "Save",
    cancel: "Cancel",
    settingsTitle: "Settings",
    darkMode: "Dark Mode",
    soundNotif: "Sound Notifications",
    language: "Language",
    nameSaved: "Name saved",
    driverOnWay: "Driver on the way",
    waitingDriver: "Waiting for driver...",
    cancelEmergency: "Cancel",
    cancelConfirm: "Do you want to cancel this request?",
    yes: "Yes",
    no: "No",
    feedbackTitle: "Leave Feedback",
    feedbackPlaceholder: "Write your comment...",
    sendFeedback: "Send",
  },
};

export const LANGUAGES = [
  { code: 'uz', label: "O'zbek", flag: '🇺🇿' },
  { code: 'ru', label: 'Русский', flag: '🇷🇺' },
  { code: 'en', label: 'English', flag: '🇬🇧' },
];

const LanguageContext = createContext(null);

export function LanguageProvider({ children }) {
  const [lang, setLang] = useState(() => localStorage.getItem('app_lang') || 'uz');

  const setLanguage = (code) => {
    setLang(code);
    localStorage.setItem('app_lang', code);
  };

  const t = translations[lang] || translations.uz;

  return (
    <LanguageContext.Provider value={{ t, lang, setLanguage, LANGUAGES }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  return useContext(LanguageContext);
}
